name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Запускать действие при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать действие при создании pull request в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/my-vsftpd:latest

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
